from enum import Enum


class ApplicationStatus(str, Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    VERIFICATION_PENDING = "VERIFICATION_PENDING"
    CREDIT_CHECK = "CREDIT_CHECK"
    LENDER_REVIEW = "LENDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    AGREEMENT_PENDING = "AGREEMENT_PENDING"
    DISBURSEMENT_INITIATED = "DISBURSEMENT_INITIATED"
    DISBURSED = "DISBURSED"
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"
